version: '3.3'
services:
  web:
    build: 
      context: ../
      dockerfile: ./DockerFiles/Dockerfile
    command: pm2-runtime index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:8080"
    env_file:
      - ./enviorment-variables.env